apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: spring
build:
  artifacts:
  - image: spring
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/web.yaml
